### ISSUE TITLE
error `JavaScript heap out of memory` while updating from v0.2.4 to v0.4.0

### ISSUE THREAD

**Issue by B2o5T** [atomiks/rehype-pretty-code#45]
Unable to build next app, found this while trying to update to the latest version
https://github.com/shuding/nextra/actions/runs/3337967625/jobs/5525004171#step:11:199

**Comment by atomiks** [comment]
JavaScript heap out of memory was introduced via https://github.com/atomiks/rehype-pretty-code/commit/8885e75ce9491986d6cb2aed1fd3d1e39e6e5309 (v0.2.4)

Then it was fixed via https://github.com/atomiks/rehype-pretty-code/commit/5fd627bcb18d435a79ef11ddaa67606314bb6bf8 (v0.3.2)

But I guess it can still happen sometimes

**Comment by atomiks** [comment]
I wonder if moving all of this code:

https://github.com/atomiks/rehype-pretty-code/blob/17e2856c5abe91eefc0830a8b5f8cab9d13aedb5/src/index.js#L64-L86

Above the `return async (tree) => {` line fixes the issue? Seems like it doesn't need to be within it.

**Comment by atomiks** [comment]
I published `v0.5.0` which hopefully fixed this. Leaving it open until it's confirmed though

**Comment by B2o5T** [comment]
issue still exists on v0.5.1 https://github.com/shuding/nextra/actions/runs/3547149625/jobs/5956958072

**Comment by atomiks** [comment]
Tried with latest `shiki` version as well? Not sure what to do to fix it that also fixes the bug @silvenon got 😕

**Comment by B2o5T** [comment]
updating shiki to latest, didn't help 😒 https://github.com/shuding/nextra/actions/runs/3550488760/jobs/5963920055

**Comment by silvenon** [comment]
@B2o5T which branch is that in your repo? I can't read CI logs that well, so I want to make sure I'm reading the correct code.

**Comment by silvenon** [comment]
`core`, I found it.

**Comment by silvenon** [comment]
A bad way to solve it on our side would be to export an additional `createRehypePrettyCodePlugin` function that provides the cache via a closure.

If Nextra was able to avoid creating a processor every time `compileMdx` was called, that would probably solve the problem on their side.

But I'm thinking about how to make it harder to fall into this trap again…

**Comment by silvenon** [comment]
I think I got it. @atomiks what do you think about `rehype-pretty-code` taking an optional `cache` as an option, where someone can pass an empty `Map()` that they create outside, once. I think that's an ok workaround for these situations which require creating a new processor on every compile.

**Comment by atomiks** [comment]
@silvenon sounds fine with me 👍

**Comment by silvenon** [comment]
Actually, I might have something better, I'll see what I can hack together in the following days…

**Comment by silvenon** [comment]
The way it's probably going to work is upgrade with no migration needed, back to global cache, but with highlighters cached under separate keys based on theme object hash.

I didn't have time to finish it today, will do it soon.

**Comment by atomiks** [comment]
@silvenon I wonder if we need to be a bit more specific, like also caching all the different options not just themes? Although caching and comparing functions might be a bit difficult. But if someone uses the same theme with a different option, it would use the stale cached version 🤔

**Comment by silvenon** [comment]
> But if someone uses the same theme with a different option, it would use the stale cached version 🤔

What do you mean? The only parameter to creating highlighters is the theme, so if the theme stays the same, the highlighter stays the same as well, unless someone changes the `getHighlighter` option, but that's probably a rarely used option anyway, so can be treated as a separate problem.

Or did you mean something else?

**Comment by atomiks** [comment]
Yeah I meant functions related to the highlighter - there's only one right now, but might be more in the future so just for future proofing's sake. Agree it's not really important right now and we can just use the theme caching.

**Comment by silvenon** [comment]
Good point, why not hash all options instead of just `theme`. 👌

**Comment by silvenon** [comment]
The PR is a draft because the tests are unexpectedly passing. I would appreciate a review and then when we figure it out it should probably be released as a pre-release to see whether it fixes the Nextra issue.

**Comment by atomiks** [comment]
@B2o5T I released @silvenon's changes as `0.6.0-beta.0` (`rehype-pretty-code@next`), can you test it out?

**Comment by B2o5T** [comment]
can confirm it was fixed in `0.6.0-beta.0`

**Comment by B2o5T** [comment]
@silvenon @atomiks I guess I found some issue that does not exist on 0.2.5 with the same version of `shiki`

https://nextra-theme-docs-pw4cdo466.vercel.sh/

on initial render `diff`'s colours defined in `theme.json` are not highlighted

https://github.com/shuding/nextra/blob/623c369e29e88598482cfb2967fdcc4076c2a05c/packages/nextra/src/theme.json#L15-L33

<img width="775" alt="image" src="https://user-images.githubusercontent.com/7361780/206922139-34e882b5-6fbb-4014-8b7a-510553198077.png">

but after navigation to (Docs) /docs and going back, they are highlighted

<img width="810" alt="image" src="https://user-images.githubusercontent.com/7361780/206922199-aaa1e645-763d-4e00-892f-0cd95d03b31d.png">

So I'll reopen this issue

**Comment by atomiks** [comment]
That's really strange, how does it get highlighted when navigating to some route then back with client side routing?

I just tried in the tests and your theme works with `diff`, what doesn't seem to work is specifying `"css-variables"` as a string for the theme, then it's missing the colors. But importing the JSON object works.

**Comment by atomiks** [comment]
I'm going to close this because it's not the same issue and is possibly unrelated (or introduced in an earlier version, as those weren't able to be tested out). 

Seems strange if it really is the same Shiki version as I can't really think what could cause it, but feel free to open a new issue for this `diff` problem
